"""Remove unique constraint from votes

Revision ID: 245286bae6e8
Revises: ab79a245a217
Create Date: 2025-07-21 11:38:34.137827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245286bae6e8'
down_revision = 'ab79a245a217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fa_qs')
    op.drop_table('follow_up')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_answer_vote', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_answer_vote', ['user_id', 'answer_id'])

    op.create_table('follow_up',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('answer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fa_qs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=255), nullable=True),
    sa.Column('answer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
